### ISSUE TITLE
installation succeeded but import failed

### ISSUE THREAD

**Issue by XJay18** [PJLab-ADG/nr3d_lib#3]
Hi, thanks for the great project!

I follow the README to install this package, and succeed in installation.
![1.png](https://x.imgs.ovh/x/2023/09/05/64f6a443115d9.png)

However, I cannot import nr3d_lib in python. I can only import nr3d_lib_bindings. Can you help me figure out why this issue appears?
![2.png](https://x.imgs.ovh/x/2023/09/05/64f6a656c543d.png)

**Comment by lxxue** [comment]
You probably need to add the parent directory to `PYTHONPATH` like [this](https://github.com/PJLab-ADG/nr3d_lib/blob/main/set_env.sh):
```
# NOTE: Insert parent directory into PYTHONPATH
# Usage: source set_env.sh


script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
script_dir=$(realpath $script_dir)
parent_dir=$(dirname $script_dir)
export PYTHONPATH="${parent_dir}":$PYTHONPATH
echo "Added $parent_dir to PYTHONPATH"
```

**Comment by XJay18** [comment]
Thanks, it works!
